# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# Cleanup live system stuff
---
# Run inside the target system (chroot)
dontChroot: false
timeout: 600
verbose: true

script:
    - "/usr/local/share/livesys/calamares/cleanup.sh"
